"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Calculator__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Calculator__factory_1 = require("./Calculator__factory");
Object.defineProperty(exports, "Calculator__factory", { enumerable: true, get: function () { return Calculator__factory_1.Calculator__factory; } });
